**NumPy Cheatsheet**

Cheatsheet for those new to Numpy

In [1]:
#import numpy
import numpy as np

In [2]:
 a=[1,2,3]
 b=[4,5,6]
 #a*b throws error

Basics

In [3]:
#initilizing arrays
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#checking dimensionality
a.ndim

1

In [6]:
#checking the shape of array
a.shape

(3,)

In [7]:
#check type and size
a.dtype

dtype('int64')

In [8]:
a = np.array([1,2,3], dtype="int16")

In [9]:
a.dtype

dtype('int16')

In [10]:
#total space in memory of one array element
a.itemsize

2

In [11]:
a = np.array([1,2,3], dtype="int64")
a.itemsize

8

In [12]:
#total space in memory for entire array
a.nbytes

24

Indexing

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [14]:
a[1, 4] #second row, fifth column

12

In [15]:
a[0, :] #first row

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
a[:, 2] #third column

array([ 3, 10])

In [17]:
a[0, 1:6:2] #from element 2 to 7 by twos

array([2, 4, 6])

In [18]:
a[0,4] = 99
a

array([[ 1,  2,  3,  4, 99,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
a[:,2] = 22 #insert 22 in third column
a

array([[ 1,  2, 22,  4, 99,  6,  7],
       [ 8,  9, 22, 11, 12, 13, 14]])

In [20]:
a[:,2] = [21, 23] #insert 21 and 23 in third column
a

array([[ 1,  2, 21,  4, 99,  6,  7],
       [ 8,  9, 23, 11, 12, 13, 14]])

Initializing arrays

In [21]:
np.zeros(10) #1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3, 5)) #2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((3, 5, 2)) #3d

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [24]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
np.full((2, 5), 22)

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [26]:
np.full_like(a, 22)

array([[22, 22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22, 22]])

In [27]:
#aternatively
np.full(a.shape, 22)

array([[22, 22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22, 22]])

In [28]:
np.random.rand(2)

array([0.08966425, 0.81639588])

In [29]:
np.random.rand(2, 5)

array([[0.68303695, 0.92944223, 0.13727609, 0.7757351 , 0.07473242],
       [0.17430128, 0.17944639, 0.97101142, 0.20142382, 0.99177993]])

In [30]:
np.random.randint(5, size=(3, 4)) #array of random ints from 0-5 (exclusive)

array([[3, 4, 3, 4],
       [2, 0, 4, 0],
       [3, 0, 2, 0]])

In [31]:
np.random.randint(3,5, size=(3, 4)) #array of random ints from 3-5 (exclusive; i.e., 3 or 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 3],
       [4, 4, 4, 3]])

In [32]:
np.identity(5) #5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a = np.array([1, 2, 3])
r = np.repeat(a, 5)
r

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [34]:
a = np.array([[1, 2, 3]])
r = np.repeat(a, 5, axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Copy an array

In [35]:
a = np.array([1, 2, 3])
b = a.copy()
b

array([1, 2, 3])

In [36]:
b[0] = 22
b

array([22,  2,  3])

In [37]:
a

array([1, 2, 3])

Maths

In [38]:
a = np.array([1,2,3,4])

In [39]:
a+2 #works with any maths operator obviously

array([3, 4, 5, 6])

In [40]:
b = np.array([4,3,2,1])

In [41]:
a+b

array([5, 5, 5, 5])

In [42]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [43]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [44]:
a = np.random.randint(5, size=(2, 3))
a

array([[2, 1, 3],
       [0, 2, 4]])

In [45]:
b = np.random.randint(3, size=(3, 2))
b

array([[1, 2],
       [2, 1],
       [0, 0]])

In [46]:
c = np.matmul(a, b) #matrix multiplication

In [47]:
np.linalg.det(c) #determinant of the matrix

-12.0

In [48]:
np.linalg.inv(c) #inverse of a matrix

array([[-0.16666667,  0.41666667],
       [ 0.33333333, -0.33333333]])

In [49]:
np.matmul(np.linalg.inv(c), c) #checks out

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

Stats

In [50]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.min(a)

1

In [52]:
np.max(a)

6

In [53]:
np.max(a, axis=1) #max of each row

array([3, 6])

In [54]:
np.max(a, axis=0) #max of each col

array([4, 5, 6])

In [55]:
np.sum(a)

21

In [56]:
np.sum(a, axis=0) #col sums

array([5, 7, 9])

Reshaping arrays

In [57]:
a = a.reshape((3,2))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
np.vstack([a, a]) #vertical stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [59]:
np.hstack([a, a]) #vhorizontal stack

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

Extras

In [60]:
#np.genfromtxt("text.txt", delimiter=",")

In [61]:
a > 2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [62]:
a[a > 2]

array([3, 4, 5, 6])

In [63]:
np.any(a > 2)

True

In [64]:
np.any(a > 2, axis=0) #apply ths function to columns

array([ True,  True])

In [65]:
np.all(a > 2)

False